CREATE INDEX "case_files_case_id_idx" ON "case_files" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "case_files_user_id_idx" ON "case_files" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "case_notes_case_id_idx" ON "case_notes" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "case_notes_user_id_idx" ON "case_notes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cases_user_id_idx" ON "cases" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cases_client_id_idx" ON "cases" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "client_portal_tokens_user_id_idx" ON "client_portal_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "client_portal_tokens_client_id_idx" ON "client_portal_tokens" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "clients_user_id_idx" ON "clients" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "document_request_items_request_id_idx" ON "document_request_items" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX "email_attachments_email_id_idx" ON "email_attachments" USING btree ("email_id");--> statement-breakpoint
CREATE INDEX "email_attachments_user_id_idx" ON "email_attachments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "events_user_id_date_time_idx" ON "events" USING btree ("user_id","date_time");--> statement-breakpoint
CREATE INDEX "events_google_event_id_idx" ON "events" USING btree ("google_event_id");--> statement-breakpoint
CREATE INDEX "events_outlook_event_id_idx" ON "events" USING btree ("outlook_event_id");--> statement-breakpoint
CREATE INDEX "events_client_id_idx" ON "events" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "emails_user_id_idx" ON "emails" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "emails_gmail_id_idx" ON "emails" USING btree ("gmail_id");--> statement-breakpoint
CREATE INDEX "emails_thread_id_idx" ON "emails" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "emails_client_id_idx" ON "emails" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "google_tokens_user_id_idx" ON "google_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "meeting_document_requests_user_id_status_idx" ON "meeting_document_requests" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "meeting_document_requests_event_id_idx" ON "meeting_document_requests" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "meeting_transcripts_meeting_id_idx" ON "meeting_transcripts" USING btree ("meeting_id");--> statement-breakpoint
CREATE INDEX "outlook_emails_user_id_idx" ON "outlook_emails" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "outlook_emails_outlook_id_idx" ON "outlook_emails" USING btree ("outlook_id");--> statement-breakpoint
CREATE INDEX "outlook_emails_conversation_id_idx" ON "outlook_emails" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "outlook_emails_client_id_idx" ON "outlook_emails" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "outlook_tokens_user_id_idx" ON "outlook_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "portal_meeting_bookings_user_id_idx" ON "portal_meeting_bookings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "portal_meeting_bookings_portal_id_idx" ON "portal_meeting_bookings" USING btree ("portal_id");--> statement-breakpoint
CREATE INDEX "portal_meeting_bookings_client_id_idx" ON "portal_meeting_bookings" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "portal_messages_portal_id_idx" ON "portal_messages" USING btree ("portal_id");--> statement-breakpoint
CREATE INDEX "portal_messages_user_id_idx" ON "portal_messages" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "scheduled_emails_user_id_idx" ON "scheduled_emails" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "scheduled_emails_status_scheduled_at_idx" ON "scheduled_emails" USING btree ("status","scheduled_at");--> statement-breakpoint
CREATE INDEX "scheduled_emails_client_id_idx" ON "scheduled_emails" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "tasks_user_id_idx" ON "tasks" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "tasks_case_id_idx" ON "tasks" USING btree ("case_id");