export const initialTasks: Task[] = [
    {
        id: 1,
        title: "Review TechCorp wireframes",
        project: "TechCorp Website Redesign",
        priority: "high",
        status: "todo",
        dueDate: "Today",
        completed: false,
    },
    {
        id: 2,
        title: "Send invoice to DesignCo",
        project: "DesignCo Brand Refresh",
        priority: "high",
        status: "todo",
        dueDate: "Today",
        completed: false,
    },
    {
        id: 3,
        title: "Update project timeline",
        project: "TechCorp Website Redesign",
        priority: "medium",
        status: "in-progress",
        dueDate: "Tomorrow",
        completed: false,
    },
    {
        id: 4,
        title: "Client meeting with StartupXYZ",
        project: "StartupXYZ MVP Development",
        priority: "high",
        status: "in-progress",
        dueDate: "Tomorrow",
        completed: false,
    },
    {
        id: 5,
        title: "Design mo" +
            "ckups review",
        project: "DesignCo Brand Refresh",
        priority: "medium",
        status: "completed",
        dueDate: "Yesterday",
        completed: false,
    },
    {
        id: 6,
        title: "Testing phase completion",
        project: "StartupXYZ MVP Development",
        priority: "low",
        status: "completed",
        dueDate: "2 days ago",
        completed: false,
    },
];