import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./index.css";
import { Navigation } from "@/app/components/Navigation";
import { headers } from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode;
}) {

    const h = await headers();            // ⬅ FIX
    const pathname = h.get("x-invoke-path") || "";

    const hideNavbarRoutes = ["/login", "/signup"];
    const hideNavbar = hideNavbarRoutes.includes(pathname);

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!hideNavbar && <Navigation />}
        {children}
        </body>
        </html>
    );
}
